### PR TITLE
Google big query

### PR DESCRIPTION
**Pull request by shannonlal**
Here is the PR for Google Big Query.  The code will build and compile.  It needs Google credentials in a file to run queries against Google Big Queries

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
I wonder if we couldn't simplify this connector by doing two things:

1. Only ask for the key file, not the project name (as it's in the file) or the database, as once you're authenticated, you can query any database in any project.
2. Don't show the left-hand sidebar, for the same reasons.

**Comment by shannonlal** [comment]
I can test adding only the key file and think that should be pretty straight forward.  For not showing the left hand side navigation would this only be for Big Query or all connectors.  We would have to modify the UI to make this work as well which would expand the PR quite a bit.  Your thoughts?

**Comment by nicolaskruchten** [comment]
I thought that for some connectors we already supported disabling the left-hand schema browser, no?

**Comment by nicolaskruchten** [comment]
Well, "support" is a strong word :) see https://github.com/plotly/falcon/blob/aca36085383e8da553686134471d96846209d682/app/components/Settings/Preview/Preview.react.js#L378

**Comment by shannonlal** [comment]
I could turn it off but it would turn it off for everyone (including users who have databases and schemas build it).  I can give it a try and see what happens

**Comment by nicolaskruchten** [comment]
Well, the alternative might be to allow users to specify full-qualified database names (e.g. `the-psf.downloads`) and use those to populate the schema browser?

**Comment by shannonlal** [comment]
@nicolaskruchten I believe that is the preview section.  The part you would want to turn off is TableTree.  This makes the call to get the schema which is where the problem comes from.  The easiest thing to do would be to make database option and only pass keyfile.  If database is defined then it would try to get the database schema information.  If the database is not defined then it would return an empty array.

This solution would allow us to contain the changes within one location (i.e. the bigquery.js file) and would not impact any changes on the UI


Does this make sense?

**Comment by nicolaskruchten** [comment]
Yes, that’s roughly what I was imagining. What do you think about
fully-qualified table names?

**Comment by nicolaskruchten** [comment]
I supposed a fully qualified database name (sorry, that’s what I meant
rather than table) basically works out to project and database like we
currently have, UX wise

**Comment by shannonlal** [comment]
Ok.  Let me look at fully qualified db names again.  It may take a bit to dig into this to see what options we have

**Comment by nicolaskruchten** [comment]
These commits were squash-merged into master. Thanks @shannonlal !

**Pull request closed without merging**
