### PR TITLE
Google big query

### PR DESCRIPTION
**Pull request by shannonlal**
@nicolaskruchten and @jackparmer Here is the PR for the Google Big Query.  It is missing two items at this point:

1. Unit testing for Google Big Query APIs
2. Refactoring the way it queries the API to get a list of tables.  From the research I have done I did not find an API call to get a list of tables and their columns in one call.  I am currently having to get a list of tables and then for each table make an api call to get its attributes.  Nico pointed out that it would not work very well if someone had a db with 100s of tables.  I figure I would submit this PR and we can go from there.

Any comments are welcome

### CODE REVIEW

**Comment by jackparmer** [comment]
Very nice, looking forward to trying this out soon

**Comment by shannonlal** [comment]
@jackparmer @nicolaskruchten anyone know what is going on with travis-ci?  It seems as though it is stuck and won't complete.  I pushed this in last night and it has been stuck for a day

**Comment by nicolaskruchten** [comment]
Not sure what's up with Travis, I'll take a look.

**Comment by nicolaskruchten** [comment]
I'll bet that Travis just builds from our repo, so could you please create a branch in this repo (rather than a fork) and push your changes up to that branch, then close this PR and open a new one from the new branch to master, and then Travis will kick in?

**Comment by nicolaskruchten** [comment]
Could I also ask that you rebase this commit onto master? I'm seeing commits with messages related to Athena which aren't really part of this diff :)

**Pull request closed without merging**
