### PR TITLE
API call counts and dropdown connection select

### LINKED ISSUE #519: API calls per day estimates
In the Query view, we should show users how many API calls per day each query will generate, along with a top-level sum of that number, and ideally somewhere above the query view, so the user can know the impact of Falcon on their API throttle, which is 10,000/day. If they have 7 "every minute" queries they'll bust that immediately.

### PR DESCRIPTION
**Pull request by briandennis**
This PR adds two features: 
- UI elements to notify the user about API call limits as well as where they stand with regard to the limits
- Refactors connection selection UI into a dropdown instead of selecting one of many static logos

closes #519

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Looking hot!

Comments on the new functionality:

- [ ] let's change the "N/10,000 API calls" and just say "N API calls per day" (I don't want to have to change Falcon if we change our plan limits)
- [ ] could we have the calls/day appear as a tooltip in the list view when hovering on the "runs at"?
- [ ] could we sort by API calls/day?

New feedback that could/should have been added to the previous PR, but I'm seeing now:

- [ ] could we have the absolute time as a tooltip in the list view and then just always show up in the modal, right after the relative time?
- [ ] could the absolute time be in ISO format? for operational uses it needs to be more precise/less ambiguous, so seconds and timezones are needed :)
- [ ] could we remove the "manage tags"  linkfrom the main list view, and just leave it in the edit modal? it feels like it clutters up the list view
- [ ] could we turn the "clear current search" link into an 'x' or something within the search box? or at least make it smaller and move it right below the search box? I don't love its current placement/prominence

**Comment by nicolaskruchten** [comment]
- [ ] I have a query that's currently "every 5 min" and it correctly shows 288 calls/day in the preview modal. In the edit modal, however, it assumes that saving it will add another 288 calls to the current total, whereas in fact saving it won't change anything because it's already contributing 288.

image

**Comment by michaelbabyn** [comment]
- [ ] Right now the API usage shows the number of API calls made per connection per day. Ideally it would show the total among all the connections but it should at least make it clear that the number reflects the calls per connection. Maybe add to @nicolaskruchten's [suggestion above](https://github.com/plotly/falcon/pull/524#issuecomment-426685276) "N calls per day from this connection"

**Comment by nicolaskruchten** [comment]
Agreed on the “for this connection” text

**Comment by briandennis** [comment]
@nicolaskruchten this should be up to date with the latest feedback

**Comment by nicolaskruchten** [comment]
I love it, thanks!

I had a few issues that I can't always replicate but I thought I'd mention:

- [ ] the preview modal sometimes gets out of sync and doesn't say "currently running" but rather "scheduled to run a few seconds ago".

image

- [ ] Sometimes the tooltips in the list view on the "runs every 5 min" don't show up (after i've played with the filter settings, adding and clearing them etc it seems to happen)

- [ ] I have a query that runs "every 1 hour" but the tooltip says "0 api calls"

- [ ] overall I find that the UI is a bit weird for "every minute" queries... it always seems to say "just now" or "in a few seconds" or "a few seconds ago" or "moments ago" and because the query is very quick, it's not clear when it's in progress vs the refresh hasn't occurred yet. Is it possible to up the refresh rate or add like a countdown-till-refresh somewhere?

**Comment by nicolaskruchten** [comment]
This looks great, thank you, sorry for the delay in reviewing!

The 0 calls thing is still present on my end:

image

I'll Slack you the connection file that causes it.

**Pull request merged**
